frequency: 50
sensor_timeout: 0.1

two_d_mode: true
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

odom0: wheel/odom
odom0_config: [true, true, false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false]
odom0_differential: false
odom0_queue_size: 5

imu0: imu/data
imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              false, false, false,
              false, false]
imu0_differential: false
imu0_queue_size: 5

gps0: /fix
gps0_config: [true,  true,  false,
              false, false, false,
              false, false, false,
              false, false, false,
              false, false]
gps0_queue_size: 5
gps0_differential: false
gps0_relative: false
