joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Wheel velocity controllers (virtual joints)
front_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: front_left_wheel_joint
  pid: {p: 5.0, i: 0.0, d: 0.1}

mid_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: mid_left_wheel_joint
  pid: {p: 5.0, i: 0.0, d: 0.1}

rear_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_left_wheel_joint
  pid: {p: 5.0, i: 0.0, d: 0.1}

front_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: front_right_wheel_joint
  pid: {p: 5.0, i: 0.0, d: 0.1}

mid_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: mid_right_wheel_joint
  pid: {p: 5.0, i: 0.0, d: 0.1}

rear_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_right_wheel_joint
  pid: {p: 5.0, i: 0.0, d: 0.1}

# Steering position controllers
front_left_steer_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_left_steer_joint
  pid: {p: 10.0, i: 0.0, d: 0.2}

front_right_steer_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_right_steer_joint
  pid: {p: 10.0, i: 0.0, d: 0.2}

rear_left_steer_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_left_steer_joint
  pid: {p: 10.0, i: 0.0, d: 0.2}

rear_right_steer_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_right_steer_joint
  pid: {p: 10.0, i: 0.0, d: 0.2}
